name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3.5.2

    - name: Install g++
      run: sudo apt-get update -y && sudo apt-get install g++ -y

    - name: Install stripios
      run : |
        wget https://raw.githubusercontent.com/Leseratte10/d2xl-cios/master/stripios/main.cpp
        g++ main.cpp -o stripios
        mv stripios ${DEVKITPRO}/tools/bin
        rm -f main.cpp

    - name: Build
      run: make -j 2

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MLOAD
        if-no-files-found: error
        path: MLOAD.app
